# 日志根配置
root:
  level: debug
  appenders:
    - file
    - console

# 日志 appender 配置
appenders:
  file:
    kind: rolling_file
    path: "app.log"
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S)} {l} {f}:{L} {t} {m}{n}"
    policy:
      trigger:
        kind: size
        limit: 10mb
      roller:
        kind: fixed_window
        pattern: "app.{}.log"
        base: 1
        count: 5
  console:
    kind: console
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S)} {l} {f}:{L} {t} {m}{n}"