- name: "Study"
  alias: 'study'
  data_type: "string"
  required: true
- name: "Site"
  alias: 'site'
  data_type: "string"
  required: true
- name: "Subject"
  alias: 'subject'
  data_type: "string"
  required: true
- name: "Folder Name"
  alias: 'folder_name'
  data_type: "string"
  required: true
- name: "Page"
  alias: 'page'
  data_type: "string"
  required: true
- name: "Entered"
  alias: 'entered'
  data_type: "integer"
  required: true
- name: "Verify Required"
  alias: 'verify_required'
  data_type: "integer"
  required: true
